name: Dino Bot

on:
  workflow_dispatch:  # Bisa dijalankan manual dari tab Actions

jobs:
  run-dino:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true  # pakai true jika kosong

    - name: Run Dino Bot
      run: python dino.py
